# -*- coding: utf-8 -*-
"""Build final HK interior material schedule Excel."""
from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

HEADERS = [
    "物料項目",
    "物料類別",
    "編碼(Item no.)",
    "應用區域",
    "品牌",
    "型號編號",
    "尺寸規格",
    "表面處理/外飾面板",
    "內籠結構/內籠面板",
    "五金配件/",
    "收口與備註",
    "數量或單位",
    "圖樣",
    "採購方式",
    "供應商聯絡電話及地址",
    "供應商網址",
    "設計師陪同選購",
    "備註",
]

ROWS: list[list[str]] = [
    [
        "石塑地板（石紋）",
        "地板",
        "FL-01",
        "客廳／飯廳、睡房／書房",
        "Cockatoo（或同等）",
        "石晶板系列（待選色號，參考901）",
        "總厚≥5.0–5.5mm；耐磨層≥0.5mm；鎖扣式；建議600×600或600×300石紋／等長條石紋",
        "UV啞光石紋面；IXPE墊層≤1.5mm",
        "—（浮鋪／鎖扣）",
        "—",
        "與吸咀F平口／金屬收邊；乾區腳線80mm；清拆舊磚後找平＋防潮膜",
        "約24–28 m²（暫估）",
        "P2 地板窗臺物料標示圖",
        "展廳／網購選樣後由裝修公司採購",
        "裝修MALL／Cockatoo代理（向平台查最新門市電話）",
        "https://mall.hkdecoman.com/product-category/%E8%A3%9D%E4%BF%AE%E4%B8%BB%E6%9D%90/%E5%9C%B0%E6%9D%BF/spc%E5%9C%B0%E6%9D%BF/",
        "是",
        "備選Quick-Step：https://int.quick-step.com/en；現場對燈核色",
    ],
    [
        "瓷質地磚 D",
        "瓷磚",
        "FL-02",
        "浴室地板",
        "鴻圖80／佛山瓷磚（或同等）",
        "F30809（或同系列選定色號）",
        "600×300mm；厚約9–10mm；吸水率≤0.5%；防滑約R10",
        "啞光／仿古面",
        "—（薄貼或傳統貼法）",
        "—",
        "向地漏找坡；與牆磚C同廠；門口接吸咀F",
        "約2.5–3.0 m²（含損耗暫估）",
        "P2；P6 浴室立面",
        "建材城現貨／訂貨",
        "鴻圖80建材城（網上查最新地址電話）",
        "https://hto80.com/",
        "是",
        "備選金銀倉：https://www.shknw.com/index.php?path=108&route=product%2Fcategory",
    ],
    [
        "瓷質地磚 E",
        "瓷磚",
        "FL-03",
        "廚房地板",
        "鴻圖80／佛山瓷磚（或同等）",
        "F30808（或與D同系列略深）",
        "600×300mm；厚約9–10mm；防滑約R10",
        "啞光",
        "—",
        "—",
        "門口接吸咀F；與牆磚A同廠",
        "約2.2–2.8 m²（含損耗暫估）",
        "P2；P7 廚房立面",
        "建材城現貨／訂貨",
        "鴻圖80建材城",
        "https://hto80.com/",
        "是",
        "與FL-02同一次訂貨減色差",
    ],
    [
        "石英石吸咀 F",
        "石材",
        "TH-01",
        "浴室門、睡房門、廚房門門檻",
        "COMPAC（Stonetech）（或同等）",
        "待選色號（建議淺灰配合SPC）",
        "厚20mm；闊度≥門扇＋兩邊各約20mm；長度現場度尺",
        "打磨拋光面",
        "—",
        "—",
        "兩側與SPC／瓷磚平口或微凸；底塗＋中性矽酮膠",
        "約3條（現場度尺）",
        "P2",
        "石材廠訂造加工＋安裝",
        "誠達建材Stonetech：灣仔駱克道362號鴻福大廈地下，電話2915 0112；辦事處2887 9398（北角炮台山木星街3號澤盈中心7樓702-5室）",
        "https://www.stonetech.com.hk/brands/compac",
        "是",
        "備選Silestone https://www.archify.com/hk/product/siliestone-hk；Caesarstone https://homejournal.hk/zh/directory/caesarstone/",
    ],
    [
        "窗臺石 G",
        "石材",
        "WS-01",
        "客廳及睡房窗臺",
        "COMPAC（Stonetech）（或同等）",
        "待選色號（建議與TH-01同色）",
        "厚20mm；深度依現有窗臺（約600mm級，現場覆核）；滿鋪",
        "打磨拋光；外側滴水線",
        "—",
        "—",
        "周邊中性矽酮膠；與窗框／牆身收口",
        "約4–6 延米×現場深度（暫估）",
        "P2",
        "石材廠訂造加工＋安裝",
        "同上Stonetech 2915 0112／2887 9398",
        "https://www.stonetech.com.hk/",
        "是",
        "盡量與TH-01、CT-B1同一石廠",
    ],
    [
        "腳線",
        "地板配件",
        "SK-01",
        "客廳、睡房等乾區（浴室廚房除外）",
        "配SPC同色／或Formica貼面",
        "待選",
        "高80mm；厚約12–15mm",
        "SPC專用腳線或MDF＋HPL",
        "—",
        "—",
        "陰角企口；遇吸咀切斷收口",
        "約35–45 延米（暫估）",
        "P2（腳線8cm）",
        "隨地板或木廠訂造",
        "隨FL-01供應商或木廠",
        "https://mall.hkdecoman.com/product-category/%E8%A3%9D%E4%BF%AE%E4%B8%BB%E6%9D%90/%E5%9C%B0%E6%9D%BF/spc%E5%9C%B0%E6%9D%BF/",
        "可選",
        "浴室／廚房改磚腳線或上翻",
    ],
    [
        "瓷磚 A",
        "瓷磚",
        "WT-A",
        "廚房牆身（一般）",
        "鴻圖80／佛山瓷磚（或同等）",
        "F30808／F30807（待選）",
        "600×300mm",
        "啞光／半啞淺色",
        "—",
        "—",
        "鋪至鋁天花底；陽角收邊條",
        "約8–12 m²（暫估）",
        "P7 廚房立面",
        "建材城",
        "鴻圖80建材城",
        "https://hto80.com/",
        "是",
        "與FL-03同廠線",
    ],
    [
        "特色瓷磚 B",
        "瓷磚",
        "WT-B",
        "廚房灶台／洗盆濺牆（枱面至吊櫃）",
        "鴻圖80／薩米特（或同等）",
        "F829／F30816（待選）",
        "600×300mm（或直鋪300×600）",
        "特色紋理／直紋／石紋",
        "—",
        "—",
        "與枱面H、吊櫃收口",
        "約1.5–3.0 m²（暫估）",
        "P7",
        "建材城／EcMall",
        "鴻圖80；薩米特見EcMall",
        "https://hto80.com/",
        "是",
        "薩米特：https://echouse.com.hk/decoration_strategy/summit-ceramic-tiles-hong-kong-exclusive-ecmall/",
    ],
    [
        "瓷磚 C",
        "瓷磚",
        "WT-C",
        "浴室牆身（一般）",
        "鴻圖80／佛山瓷磚（或同等）",
        "F30809（待選，與FL-02同系）",
        "600×300mm",
        "啞光淺色",
        "—",
        "—",
        "滿高至鋁天花；與地磚D對縫",
        "約10–14 m²（暫估）",
        "P6 浴室立面",
        "建材城",
        "鴻圖80建材城",
        "https://hto80.com/",
        "是",
        "",
    ],
    [
        "特色瓷磚 D",
        "瓷磚",
        "WT-D",
        "浴室浴缸／淋浴背牆",
        "鴻圖80／薩米特（或同等）",
        "F829／F30815（待選）",
        "600×300mm",
        "特色對比面",
        "—",
        "—",
        "淋浴區加強防水後貼磚",
        "約2–4 m²（暫估）",
        "P6",
        "建材城",
        "鴻圖80／EcMall",
        "https://hto80.com/",
        "是",
        "",
    ],
    [
        "防水系統",
        "防水物料",
        "WP-01",
        "浴室全面；廚房濕區",
        "Sika（或同等）",
        "SikaTop-107 Seal HK＋SikaLatex 700等配套",
        "按廠方用量；牆上翻≥150mm；淋浴≥300mm",
        "水泥基彈性防水塗層",
        "—",
        "—",
        "鋪磚前強制蓄水試驗；陰陽角加強",
        "浴室約3–4 m²地＋牆上翻；廚房濕區另計",
        "設計圖註全面防水；P6",
        "五金／建材行或經泥水採購",
        "西卡香港分銷查詢 +852 9447 0107（以官網為準）",
        "https://hkg.sika.com/zh/distribution-retail/household_waterproofing/kitchen_and_bathroom.html",
        "否",
        "備選Mapei Mapelastic（香港五金網有售）",
    ],
    [
        "廚櫃枱面人造石 H",
        "枱面石材",
        "CT-H",
        "廚房K1枱面",
        "Corian®（DuPont）",
        "待選色號（建議白／淺灰）",
        "厚12mm；長度現場度尺；無縫駁口",
        "啞光／半啞實體面材",
        "—（實心人造石）",
        "星盆開孔按選定盆具",
        "靠牆矽酮膠或薄上翻；灶位預留",
        "約2.5–3.5 延米（暫估）",
        "P7；設計圖K1",
        "授權代理訂造加工＋安裝",
        "Speed Top (HK)：九龍長沙灣道681號貿易廣場9樓909-910室；電話+852 2435 4427",
        "https://speedtop-hk.com/colors_of_corian/",
        "是",
        "備選Lexton／Staron：http://mail.lexton.com.hk/",
    ],
    [
        "浴室洗手櫃枱面",
        "枱面石材",
        "CT-B1",
        "浴室洗面盆櫃B1",
        "COMPAC石英石（或Corian）",
        "待選（建議與TH-01同色）",
        "厚20mm石英石（或Corian 12mm）；闊配B1櫃",
        "打磨拋光",
        "—",
        "底掛／半嵌盆五金",
        "盆周矽酮膠；背後靠牆收口",
        "1套（現場度尺）",
        "P6 B1",
        "石材／人造石廠訂造",
        "Stonetech 2915 0112 或 Speed Top 2435 4427",
        "https://www.stonetech.com.hk/",
        "是",
        "濕區優先石英石",
    ],
    [
        "裝飾耐火板（外飾）",
        "木器飾面板",
        "CB-HPL",
        "全屋固定傢俬外露面：L1–L4、S1–S3、K1–K2、B1等",
        "Formica®（或同等）",
        "待選：木紋1款＋素色1款（銀鏡面用於圖示位置）",
        "HPL 0.7–1.0mm；按門板分拆表",
        "防火／耐火級飾面板（需時選FR）",
        "貼於18mm夾板門板／側板",
        "—",
        "邊緣同色封邊條",
        "按木器展開面積（木廠計料）",
        "P1設計圖；P4–P7立面",
        "展廳選樣→木廠採購裱貼",
        "Formica展廳：灣仔告士打道66號地下；電話+852 2155 5183；辦公室北角英皇道255號奧林匹亞廣場13樓1305-9室",
        "https://shop.formica.com.hk/",
        "是",
        "備選LAMITAK：灣仔駱克道275-277號金樂大廈1樓B室 https://www.lamitak.com/pages/locate-us-hongkong；Wilsonart https://www.wilsonartasia.com/",
    ],
    [
        "耐磨／防潮夾層板（櫃身）",
        "木器基板",
        "CB-PLY",
        "全屋櫃身、層板、床箱等",
        "優質夾板（E0／E1）",
        "18mm防潮夾板（廚／浴用防潮級）",
        "側板／門板18mm；層板按設計；背板約9mm",
        "—",
        "內籠18mm夾板；內面白膠板或同系HPL",
        "—",
        "濕區櫃底升高／防水腳；見光面封邊",
        "按木廠計料",
        "P1；P4–P7",
        "木廠採購",
        "經承造木廠",
        "—",
        "否",
        "K2圖註可用針葉夾板＋耐火板",
    ],
    [
        "木器五金",
        "五金",
        "HW-01",
        "所有櫃門、櫃桶",
        "Blum（或同等）",
        "Clip top緩衝鉸；TANDEMBOX／LEGRABOX路軌（木廠選配）",
        "按門扇／櫃桶尺寸",
        "—",
        "—",
        "緩衝鉸、緩衝路軌、衣通、層板釘；B1暗抽手",
        "按廠方間距安裝及調較",
        "1套（跟木器）",
        "P4–P7",
        "木廠經授權代理採購",
        "Blum香港產品查詢（經木廠／代理）",
        "https://www.blum.com/hk/en/products/product-world/",
        "可選",
        "可同等Hettich https://www.hettich.com/",
    ],
    [
        "衣櫃金屬架",
        "金屬配件",
        "HW-S1",
        "睡房半開放衣櫃S1",
        "訂造噴粉鋼／鋁架",
        "啞黑／香檳金（待選）",
        "按S1立面（約1624mm闊級，現場覆核）",
        "噴粉啞光",
        "金屬立柱＋層板托",
        "可調層板釘",
        "與耐火板層板穩固交接",
        "1套",
        "P5 睡房立面",
        "金屬廠／木廠統包",
        "經承造商",
        "—",
        "是",
        "金屬色全屋統一",
    ],
    [
        "B2金屬架＋鏡",
        "金屬／玻璃",
        "HW-B2",
        "浴室半身凹口儲物架B2",
        "訂造",
        "金屬架＋直鑲鏡",
        "按P6半身高尺寸",
        "金屬噴粉；鏡面",
        "—",
        "底滲光燈槽",
        "鏡邊密封防潮",
        "1套",
        "P6",
        "金屬／玻璃廠",
        "經承造商",
        "—",
        "是",
        "配防水LED",
    ],
    [
        "鋁板假天花",
        "天花",
        "CL-01",
        "廚房、浴室",
        "Hunter Douglas 樂思龍（或同等）",
        "300C／300L 寬板",
        "板寬300mm；RAL白／淺灰",
        "噴粉鋁面；可選微孔",
        "鋁龍骨系統",
        "—",
        "可拆面板方便檢修；周邊收邊條",
        "廚＋浴約5–7 m²（暫估）",
        "P3；P6；P7",
        "天花工程公司經代理",
        "Hunter Douglas亞太查香港代理（官網）",
        "https://ap.hunterdouglas.asia/hk/product/interior-metal-wide-panel/interior-metal-300c-l",
        "可選",
        "圖紙註300闊鋁板假天花",
    ],
    [
        "石膏板假天花＋燈槽",
        "天花",
        "CL-02",
        "客廳／飯廳（含燈槽木殼）",
        "一般石膏板系統",
        "12.5mm石膏板＋金屬龍骨",
        "假天花約+2242／+2250（以圖為準）",
        "批盪＋乳膠漆；燈槽木殼可油漆木紋",
        "金屬吊架／龍骨",
        "滲光燈帶鋁槽＋擴散罩",
        "與樑／原天花交接；預留冷氣喉位",
        "約客廳範圍（現場計）",
        "P3；P4",
        "裝修泥水／天花判",
        "經承造商",
        "—",
        "否",
        "",
    ],
    [
        "乳膠漆",
        "油漆",
        "PT-01",
        "一般牆身、石膏板天花",
        "多樂士 Dulux（或同等）",
        "超耐洗／淨味系列（待選色號，建議白／淺灰）",
        "按面積",
        "平光／蛋殼光；低VOC",
        "—",
        "—",
        "底漆＋面漆最少兩度；濕區天花加防霉",
        "約牆＋天花80–100 m²（暫估）",
        "P3註油漆",
        "油漆行／經承造商",
        "多樂士客戶服務 +852 2823 1388；北角英皇道510號港運大廈2806室",
        "https://www.dulux.com.hk/",
        "是（選色）",
        "備選立邦 https://www.nipponpaint.com.hk/",
    ],
    [
        "特色藝術漆",
        "油漆",
        "PT-02",
        "睡房特色藝術油漆牆",
        "Oikos／Novacolor（或同等）",
        "待選效果及色號",
        "按立面面積",
        "藝術肌理效果",
        "—",
        "可配金屬拉線飾",
        "按廠方底塗系統",
        "約1面牆（現場計）",
        "P5",
        "授權經銷展廳",
        "經藝術漆代理（請展廳確認電話地址）",
        "—",
        "是",
        "與PT-01色系協調",
    ],
    [
        "廚房兩小時防火門",
        "門",
        "DR-FD",
        "廚房門",
        "戶信／認可防火門廠（或同等）",
        "FD120防火門組",
        "門扇配洞口（現場度尺）；高約2100mm級",
        "面層配合室內（耐火板／油漆）",
        "防火門芯＋防火門框",
        "防火鉸、閉門器、防火鎖等",
        "須附測試報告／認證；核屋苑規定",
        "1樘",
        "P7；設計圖註兩小時防火門",
        "防火門專業供應商訂造安裝",
        "戶信防火隔音建材（請官網查最新電話地址）",
        "https://www.firedoor.com.hk/",
        "可選",
        "備選https://www.ulsteel.com.hk/fire_rated_steel_door_transformer_room_door/；落標前確認是否必須FD120",
    ],
    [
        "浴室門（連底百葉）",
        "門",
        "DR-B",
        "浴室",
        "木廠訂造",
        "HPL／油漆門",
        "約810mm闊級（以P6為準）；高約2100mm",
        "耐火板或油漆",
        "實心／半實心門扇",
        "緩衝鉸；門底通風百葉",
        "更換門框；與磚牆收口",
        "1樘",
        "P6",
        "木廠統包",
        "經承造木廠",
        "—",
        "是",
        "百葉利通風",
    ],
    [
        "其他內門",
        "門",
        "DR-01",
        "睡房等內門（更換門框門扇）",
        "木廠訂造",
        "HPL／油漆門",
        "現場度尺",
        "耐火板或油漆",
        "—",
        "緩衝鉸、門鎖",
        "全屋內門框扇更換",
        "按實際樘數",
        "設計圖註",
        "木廠",
        "經承造商",
        "—",
        "是",
        "",
    ],
    [
        "座廁",
        "潔具",
        "SW-01",
        "浴室",
        "TOTO",
        "CW766PB／SW766HK（或同等座地雙段沖水）",
        "約724×408×777mm（以官網為準）；核rough-in",
        "釉面陶瓷",
        "—",
        "水箱配件、油壓廁板",
        "排污位現場核實後落單",
        "1套",
        "P6",
        "授權經銷商",
        "TOTO Showroom：灣仔駱克道41號東城大廈1樓；其他經銷商見官網",
        "https://hk.toto.com/en/product/toilet/CW766PB-SW766HK",
        "是",
        "經銷商：https://hk.toto.com/en/location",
    ],
    [
        "面盆",
        "潔具",
        "SW-02",
        "浴室B1",
        "TOTO／American Standard（或同等）",
        "待選底掛／半嵌盆（配合CT-B1開孔）",
        "按枱面開孔",
        "釉面",
        "—",
        "去水、溢流",
        "與石面矽酮膠密封",
        "1個",
        "P6",
        "授權店",
        "TOTO／美標授權店",
        "https://www.americanstandard.hk/zh-hant/bathroom/",
        "是",
        "",
    ],
    [
        "浴缸",
        "潔具",
        "SW-03",
        "浴室",
        "TOTO／美標／亞加力缸（或同等）",
        "待選；約700×1500級（圖示約700闊，現場覆核）",
        "以現場度尺為準",
        "亞加力或搪瓷鋼",
        "—",
        "去水、溢流、龍頭預留",
        "浴缸周邊防水加強",
        "1隻",
        "P6",
        "授權店／潔具店",
        "灣仔駱克道潔具街一帶授權店",
        "https://hk.toto.com/en/home",
        "是",
        "尺寸必須現場覆核",
    ],
    [
        "淋浴花灑及龍頭",
        "潔具五金",
        "SW-04",
        "浴室淋浴／面盆／廚房",
        "Hansgrohe（或同等）",
        "待選系列（面盆＋淋浴／浴缸＋廚房龍頭）",
        "按牆體預留冷熱水位",
        "鉻或啞黑",
        "—",
        "角閥、軟管",
        "只經授權店以保保養",
        "浴室1套＋廚房龍頭另計",
        "P6；P7",
        "授權經銷商",
        "Hansgrohe香港授權店（灣仔駱克道等多間，見官網名單）",
        "https://www.hansgrohe-asia.com/en/hkdealers",
        "是",
        "備選GROHE https://www.grohe.com/en-HK/",
    ],
    [
        "半身玻璃浴屏",
        "玻璃金屬",
        "SW-05",
        "浴缸邊淋浴分隔",
        "訂造",
        "半身高強化玻璃連金屬框",
        "玻璃厚8–10mm；高度按P6",
        "清玻；金屬框啞黑／鉻",
        "—",
        "固定夾、密封膠條",
        "底部坐缸邊防水",
        "1套",
        "P6",
        "玻璃廠訂造",
        "經承造商",
        "—",
        "是",
        "",
    ],
    [
        "磁吸軌道燈",
        "燈具",
        "LG-01",
        "客廳",
        "Philips／歐普／本地磁吸系統（或同等）",
        "48V磁吸軌道＋射燈模組",
        "軌道長度按P3布置",
        "黑／白色軌道",
        "—",
        "驅動電源",
        "天花預留電源及檢修",
        "1套（兩軌道級，按圖）",
        "P3",
        "燈飾店／電業",
        "灣仔／深水埗燈飾店",
        "—",
        "是",
        "3000K；CRI≥90",
    ],
    [
        "滲光LED燈帶",
        "燈具",
        "LG-02",
        "假天花燈槽、木器滲光位",
        "優質LED燈帶",
        "3000K；CRI≥90；乾區IP20；濕區燈槽建議IP65",
        "按燈槽延米",
        "鋁槽＋PC擴散罩",
        "—",
        "驅動器",
        "預留電源",
        "按圖延米",
        "P3；P4–P7",
        "燈飾／電業經承造",
        "經承造商",
        "—",
        "可選",
        "",
    ],
    [
        "防水防潮筒燈",
        "燈具",
        "LG-03",
        "廚房、浴室",
        "嵌入式LED",
        "7–9W；IP44及以上；3000K",
        "開孔按選型",
        "白色面環",
        "—",
        "—",
        "配鋁天花裁孔",
        "按圖數量（暫估各室2–4）",
        "P3；P6；P7",
        "燈飾店",
        "經承造商／燈飾店",
        "—",
        "可選",
        "另有5W氣氛小筒燈按圖",
    ],
]


def main() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "物料規格表"

    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(bold=True, color="FFFFFF", name="Microsoft YaHei", size=10)
    cell_font = Font(name="Microsoft YaHei", size=9)
    wrap = Alignment(wrap_text=True, vertical="top")
    thin = Border(
        left=Side(style="thin", color="B0B0B0"),
        right=Side(style="thin", color="B0B0B0"),
        top=Side(style="thin", color="B0B0B0"),
        bottom=Side(style="thin", color="B0B0B0"),
    )
    zebra = PatternFill("solid", fgColor="F2F2F2")

    for col, h in enumerate(HEADERS, 1):
        cell = ws.cell(1, col, h)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")
        cell.border = thin

    for r_idx, row in enumerate(ROWS, 2):
        assert len(row) == len(HEADERS), (r_idx, len(row))
        for c_idx, val in enumerate(row, 1):
            cell = ws.cell(r_idx, c_idx, val)
            cell.font = cell_font
            cell.alignment = wrap
            cell.border = thin
            if r_idx % 2 == 0:
                cell.fill = zebra

    widths = [18, 12, 14, 22, 18, 28, 28, 22, 20, 20, 28, 16, 18, 18, 36, 40, 12, 36]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    ws.row_dimensions[1].height = 32
    for r in range(2, len(ROWS) + 2):
        ws.row_dimensions[r].height = 55

    ws.auto_filter.ref = f"A1:R{len(ROWS) + 1}"
    ws.freeze_panes = "C2"

    ws2 = wb.create_sheet("填表說明")
    notes = [
        ["欄位", "說明"],
        ["編碼(Item no.)", "對應圖紙物料代號（FL地板、WT牆磚、CT枱面、CB木器、SW潔具等）"],
        ["品牌／型號", "已填建議首選；未定色號標「待選」—請設計師陪同展廳落實後更新本表"],
        ["數量或單位", "按約36m²單位及圖紙暫估，招標前須現場覆核"],
        ["圖樣", "對應 tender PDF 圖號（P2地板、P3天花、P4–P7立面等）"],
        ["設計師陪同選購", "「是」=建議帶樣板／色卡親選"],
        ["備註", "含同等品牌替代連結；招標可寫「或同等品質」"],
        ["版本", "Rev.00 | 2026-08-27 | 約36m²住宅裝修物料規格表"],
    ]
    for r, row in enumerate(notes, 1):
        for c, v in enumerate(row, 1):
            cell = ws2.cell(r, c, v)
            cell.font = Font(name="Microsoft YaHei", size=10, bold=(r == 1))
            cell.alignment = wrap
    ws2.column_dimensions["A"].width = 20
    ws2.column_dimensions["B"].width = 80

    outs = [
        Path(r"c:\Users\Rico\Downloads\Material_Schedule_HK_36sqm_Final.xlsx"),
        Path(r"c:\Users\Rico\Downloads\material_schedule_final.xlsx"),
        Path(r"c:\Users\Rico\PycharmProjects\Skills-Architects-HK\.tmp_tender_pages\material_schedule_final.xlsx"),
    ]
    for p in outs:
        wb.save(p)
        print("saved", p.name, "bytes", p.stat().st_size, "rows", len(ROWS))


if __name__ == "__main__":
    main()
